-- Insert default permissions for all pages
INSERT INTO crud_permissions (role, page, can_create, can_edit, can_delete) VALUES
-- Super Admin permissions (full access)
('super admin', 'ready', true, true, true),
('super admin', 'gudang', true, true, true),
('super admin', 'produksi', true, true, true),
('super admin', 'produksi_detail', true, true, true),
('super admin', 'analysis', true, true, true),
('super admin', 'esb', true, true, true),
('super admin', 'product_name', true, true, true),
('super admin', 'categories', true, true, true),
('super admin', 'recipes', true, true, true),
('super admin', 'supplier', true, true, true),
('super admin', 'branches', true, true, true),
('super admin', 'users', true, true, true),
('super admin', 'stock_opname', true, true, true),
('super admin', 'product_settings', true, true, true),
('super admin', 'permissions-db', true, true, true),

-- Admin permissions (full access)
('admin', 'ready', true, true, true),
('admin', 'gudang', true, true, true),
('admin', 'produksi', true, true, true),
('admin', 'produksi_detail', true, true, true),
('admin', 'analysis', true, true, true),
('admin', 'esb', true, true, true),
('admin', 'product_name', true, true, true),
('admin', 'categories', true, true, true),
('admin', 'recipes', true, true, true),
('admin', 'supplier', true, true, true),
('admin', 'branches', true, true, true),
('admin', 'users', true, true, true),
('admin', 'stock_opname', true, true, true),
('admin', 'product_settings', true, true, true),
('admin', 'permissions-db', true, true, true),

-- Finance permissions (read-only)
('finance', 'ready', false, false, false),
('finance', 'gudang', false, false, false),
('finance', 'produksi', false, false, false),
('finance', 'produksi_detail', false, false, false),
('finance', 'analysis', false, false, false),
('finance', 'esb', false, false, false),
('finance', 'product_name', false, false, false),
('finance', 'categories', false, false, false),
('finance', 'recipes', false, false, false),
('finance', 'supplier', false, false, false),
('finance', 'branches', false, false, false),
('finance', 'users', false, false, false),
('finance', 'stock_opname', false, false, false),
('finance', 'product_settings', false, false, false),
('finance', 'permissions-db', false, false, false),

-- PIC Branch permissions (create + edit, no delete for operational pages)
('pic branch', 'ready', true, true, false),
('pic branch', 'gudang', true, true, false),
('pic branch', 'produksi', true, true, false),
('pic branch', 'produksi_detail', true, true, false),
('pic branch', 'analysis', false, false, false),
('pic branch', 'esb', false, false, false),
('pic branch', 'product_name', false, false, false),
('pic branch', 'categories', false, false, false),
('pic branch', 'recipes', false, false, false),
('pic branch', 'supplier', false, false, false),
('pic branch', 'branches', false, false, false),
('pic branch', 'users', false, false, false),
('pic branch', 'stock_opname', true, true, false),
('pic branch', 'product_settings', false, false, false),
('pic branch', 'permissions-db', false, false, false),

-- Staff permissions (create only for basic operations)
('staff', 'ready', true, false, false),
('staff', 'gudang', true, false, false),
('staff', 'produksi', true, false, false),
('staff', 'produksi_detail', false, false, false),
('staff', 'analysis', false, false, false),
('staff', 'esb', false, false, false),
('staff', 'product_name', false, false, false),
('staff', 'categories', false, false, false),
('staff', 'recipes', false, false, false),
('staff', 'supplier', false, false, false),
('staff', 'branches', false, false, false),
('staff', 'users', false, false, false),
('staff', 'stock_opname', false, false, false),
('staff', 'product_settings', false, false, false),
('staff', 'permissions-db', false, false, false)

ON CONFLICT (role, page) DO UPDATE SET
  can_create = EXCLUDED.can_create,
  can_edit = EXCLUDED.can_edit,
  can_delete = EXCLUDED.can_delete;